# Generated by Django 6.0.5 on 2026-05-16 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LottoRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_num', models.PositiveIntegerField(unique=True)),
                ('draw_date', models.DateTimeField(auto_now_add=True)),
                ('num1', models.PositiveIntegerField(blank=True, null=True)),
                ('num2', models.PositiveIntegerField(blank=True, null=True)),
                ('num3', models.PositiveIntegerField(blank=True, null=True)),
                ('num4', models.PositiveIntegerField(blank=True, null=True)),
                ('num5', models.PositiveIntegerField(blank=True, null=True)),
                ('num6', models.PositiveIntegerField(blank=True, null=True)),
                ('bonus_num', models.PositiveIntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.PositiveIntegerField()),
                ('num2', models.PositiveIntegerField()),
                ('num3', models.PositiveIntegerField()),
                ('num4', models.PositiveIntegerField()),
                ('num5', models.PositiveIntegerField()),
                ('num6', models.PositiveIntegerField()),
                ('is_auto', models.BooleanField(default=True)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('prize', models.PositiveIntegerField(default=0)),
                ('lotto_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottos.lottoround')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=10000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
