# Generated by Django 6.0.5 on 2026-05-16 19:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lottoround',
            name='bonus_num',
        ),
        migrations.RemoveField(
            model_name='lottoround',
            name='draw_date',
        ),
        migrations.RemoveField(
            model_name='lottoround',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='lottoround',
            name='round_num',
        ),
        migrations.AddField(
            model_name='lottoround',
            name='bonus',
            field=models.PositiveIntegerField(default=0, verbose_name='보너스 번호'),
        ),
        migrations.AddField(
            model_name='lottoround',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='추첨 일시'),
        ),
        migrations.AddField(
            model_name='lottoround',
            name='round_number',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='회차'),
        ),
        migrations.AlterField(
            model_name='lottoround',
            name='num1',
            field=models.PositiveIntegerField(default=0, verbose_name='번호 1'),
        ),
        migrations.AlterField(
            model_name='lottoround',
            name='num2',
            field=models.PositiveIntegerField(default=0, verbose_name='번호 2'),
        ),
        migrations.AlterField(
            model_name='lottoround',
            name='num3',
            field=models.PositiveIntegerField(default=0, verbose_name='번호 3'),
        ),
        migrations.AlterField(
            model_name='lottoround',
            name='num4',
            field=models.PositiveIntegerField(default=0, verbose_name='번호 4'),
        ),
        migrations.AlterField(
            model_name='lottoround',
            name='num5',
            field=models.PositiveIntegerField(default=0, verbose_name='번호 5'),
        ),
        migrations.AlterField(
            model_name='lottoround',
            name='num6',
            field=models.PositiveIntegerField(default=0, verbose_name='번호 6'),
        ),
        migrations.CreateModel(
            name='LottoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('AUTO', '자동'), ('MANUAL', '수동')], max_length=10, verbose_name='구매 방식')),
                ('num1', models.PositiveIntegerField(default=0)),
                ('num2', models.PositiveIntegerField(default=0)),
                ('num3', models.PositiveIntegerField(default=0)),
                ('num4', models.PositiveIntegerField(default=0)),
                ('num5', models.PositiveIntegerField(default=0)),
                ('num6', models.PositiveIntegerField(default=0)),
                ('is_checked', models.BooleanField(default=False, verbose_name='당첨 확인 여부')),
                ('rank', models.IntegerField(default=-1, verbose_name='당첨 등수')),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='구매 일시')),
                ('lotto_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lottos.lottoround', verbose_name='해당 회차')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='구매자')),
            ],
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
